### ISSUE TITLE
Quelques problèmes sur le calcul d'offre de sièges

### ISSUE THREAD

**Issue by victor77420** [erialc-cal/StatApp_2020#1]
- Le programme prend un an à tourner car y'a beaucoup de données
- Y'a certaines valeurs aberrantes (offre inférieure au nombre réalisé) : je sais pas si ça vient de mon programme ou des données qui collent pas ensemble)

**Comment by erialc-cal** [comment]
Je ne pense pas que ça vienne de ton programme ! Il y a une certaine élasticité au nombre de sièges (un A320 va afficher une capacité de 140 personnes mais va pouvoir en accueillir un peu plus, le choix est fait par la compagnie, les avions supportent davantage un poids qu'un nombre fixe de personnes : par exemple les easy jets vont être saturés niveau passagers je pense et la compagnie exige moins de bagages/plus légers qu'un long courrier), il faut voir en revanche à combien l'offre est inférieure au nombre réalisé !

**Comment by victor77420** [comment]
okkkkkk thank you ! je ferme l'issue
